# -*- coding: utf-8 -*-
"""EN23107085(AIPD-9).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCbXXpDK1gxCWbm4EIxa4ASzLwkKsxya

## Assignment No:9

Name :Nikam Sakshi Jalindar

Roll No:2317085

Batch:A

Title:Develop an AI model to analyze social media sentiment trends for financial markets.
"""

#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

#Load Your Dataset
df = pd.read_csv("data.csv")

print(df.head())
print(df.columns)

#Data Preprocessing
# Rename columns if needed
df.columns = df.columns.str.lower()

# Example (adjust if names differ)
text_col = 'text' if 'text' in df.columns else df.columns[0]
label_col = 'sentiment' if 'sentiment' in df.columns else df.columns[-1]

# Remove null values
df = df[[text_col, label_col]].dropna()

print(df.head())

#Convert Text → Features (TF-IDF)
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)

X = vectorizer.fit_transform(df[text_col])
y = df[label_col]

#Train Model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

#Evaluate Model
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

#Convert sentiment to numeric
sentiment_map = {
    'positive': 1,
    'neutral': 0,
    'negative': -1
}

df['sentiment_score'] = df[label_col].map(sentiment_map)

#Plot Sentiment Distribution
df[label_col].value_counts().plot(kind='bar')
plt.title("Sentiment Distribution")
plt.show()

#Sentiment Trend (Simulated Time Series)

df['index'] = range(len(df))

plt.plot(df['index'], df['sentiment_score'])
plt.title("Sentiment Trend Over Time")
plt.xlabel("Time")
plt.ylabel("Sentiment")
plt.show()

#Financial Insight (Basic Simulation)

avg_sentiment = df['sentiment_score'].mean()
print("Average Market Sentiment:", avg_sentiment)

#Predict New Tweet Sentiment
def predict_sentiment(text):
    vec = vectorizer.transform([text])
    pred = model.predict(vec)
    return pred[0]

print(predict_sentiment("Stock market is going up strongly"))

